services:
  # Backend API Service
  - type: web
    name: fileupdown-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fileupdown-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_DIR
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 104857600
      - key: CORS_ORIGINS
        value: https://fileupdown-frontend.onrender.com
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: fileupdown-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://fileupdown-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true

databases:
  - name: fileupdown-db
    databaseName: fileupdown
    user: fileupdown
    plan: free 